version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    ports:
      - ${BJ_PORT}:${BJ_PORT}
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    env_file:
      - .docker.env
    ports:
      - "5434:5432"
    restart: unless-stopped